language: node_js
node_js: 10
sudo: required
before_script: npm install -g polymer-cli @advanced-rest-client/wct-istanbub
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run polymer test --module-resolution=node --npm --plugin local
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test
    --module-resolution=node --npm --plugin sauce --job-name
    "cookie-parser:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}; fi
env:
  global:
    - secure: >-
        cbgembXLt7MDBt+tb3uJ9+BIjH41RRgJ3/vsfATWLkMb3O5XRwJy6QLOtM1FoWqSstbN6UBxlfg4xtXseTZQhO8Fd/tjUr5mtSH5zEYoehTIoXFeuAUvU2FtTKk6F2WwT3jLc0TmA/Q2tkPchPPBZfgL7yrbT91TynzwC8lwB3OPgrSO35ZncGw4Z6+207E0KOACqrLYqoyDQmCgX2SP/O22nueGKrqCBAK4jPzgwFEOWWanhZmS3xn7uSz5RBHSJp2jdtcQbepdce7T6D8pW0FfyEdKfNCMX4UXld6GXVVUbno4r2S3MYVOB12ztv8ffHFVGY1Ds0E5D+T5IlrL/4sSVLXFvDE5ckU+uf1XuSgm4WkdA8pMmTtObDIZUHyIYRoC2cTJ8TkglP8tNnYuq8/mvFVtXucPeM1Agq78/r+W32KFYFflzbDvafKOVljkaVBMTpchErYRGi0dKSO/DTjF8kKNRKnYMs+6AjMyM2WszX9c5mOkGBdIQS9axz9xsvcOqdpHlkuqyttjS/S+gnQuIuZnKpUYUyQtfxPBvJhuMOMW4rL215A1rwatGydiX6q4oUF/UrK5zXxH0MZ80/z2ZYt+MhcBOFbRXs0hhUkHPPElRqNOFnKZTOZC+DhiDfV2+jZo1Dk4TFN6IFdUAb3CCAI0DIQpOkL1Fcsnn0c=
    - secure: >-
        oGyynQ39IjFAnhd1WBnG1JXtGVxg2mHkIC2c/M2QIN2BpQozierhKQEDnagzGnWhlO10hHoTx3NXh933NAgq9MwikXaN2WwvOoLPjz51YSNUNHNIiSjnPjpKW5lTqb/w/NTVG9JUXO/fUMXHSTGYK16BmvCer7fYYehEgpmK3HYWwsiOL+ZNOcAm8znvQ5VDTrYX9hyq/ts2v+apS//x45FVYXiVhzRPIcfi3ag/kXEbIbBd+5UR70ZsXcd52EU/mJZMpXMsqC1ULRB9DTOqYBL5VOTiIjjW65cwJPuMczz9LNQ5x/VIC06ixn36A2Ulrv1l5g0XvgJ8EHQHiQJkopcfLoiu9bNO9saaVY6Gsa8ijGC8NsQwY0a7CVXIQeV/PFH3NTy+LZ4SHSvGGh1+ia3FR5iyUhW9hdZk0KFvRc1hqlZ3B3wzh6Kl47S7Ye3WgzPQXGSHkLQJD8FyWmSiD2m3G0+RYBkP1nt1OaMg0ttH3VQ5xOZh/XG0BMhvnvVZ4XdjFXx4xAQlkn+mDtL1koDXQynd1EHwY0o/AZOA5yzASGVW29e2ktevALVDXmC0tMf2xvroSAPGKgwwoqsXh4e7LKAFwk91iM5av9tOnuoniMexP9zEsyMDGXufcdAYRSQWS43yOnXdD2gUBTzrkLdrijoD5k8o6V+7kyrMs7s=
